# Generated by Django 5.2.4 on 2025-07-10 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon (FontAwesome)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hizmet Kategorisi',
                'verbose_name_plural': 'Hizmet Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('duration', models.IntegerField(verbose_name='Süre (Dakika)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('image', models.ImageField(blank=True, upload_to='service_images/', verbose_name='Hizmet Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Müsait')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salonemployee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='services.service')),
            ],
            options={
                'verbose_name': 'Hizmet Çalışanı',
                'verbose_name_plural': 'Hizmet Çalışanları',
                'unique_together': {('service', 'employee')},
            },
        ),
    ]
