# Generated by Django 5.2.4 on 2025-07-10 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer')], max_length=10, verbose_name='Cinsiyet')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('profile_image', models.ImageField(blank=True, upload_to='customer_profiles/', verbose_name='Profil Fotoğrafı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
    ]
