# Generated by Django 5.2.4 on 2025-07-12 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_points',
            field=models.IntegerField(default=0, verbose_name='Mevcut Puan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_level',
            field=models.CharField(choices=[('bronze', 'Bronz'), ('silver', 'Gümüş'), ('gold', 'Altın'), ('platinum', 'Platin')], default='bronze', max_length=20, verbose_name='Sadakat Seviyesi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Toplam Puan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Harcama'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_visits',
            field=models.IntegerField(default=0, verbose_name='Toplam Ziyaret'),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(verbose_name='Puan')),
                ('reason', models.CharField(max_length=200, verbose_name='Sebep')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Puan Geçmişi',
                'verbose_name_plural': 'Puan Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
