# Generated by Django 5.2.4 on 2025-07-10 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Salon Adı')),
                ('salon_type', models.CharField(choices=[('kuafor', 'Kuaför'), ('berber', 'Berber'), ('guzellik_salonu', 'Güzellik Salonu'), ('spa', 'Spa & Masaj'), ('manikur', 'Manikür & Pedikür'), ('diger', 'Diğer')], max_length=20, verbose_name='Salon Türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('opening_time', models.TimeField(verbose_name='Açılış Saati')),
                ('closing_time', models.TimeField(verbose_name='Kapanış Saati')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Ortalama Puan')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Toplam Değerlendirme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış')),
                ('logo', models.ImageField(blank=True, upload_to='salon_logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, upload_to='salon_covers/', verbose_name='Kapak Fotoğrafı')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkında')),
                ('photo', models.ImageField(blank=True, upload_to='employee_photos/', verbose_name='Fotoğraf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Salon Çalışanı',
                'verbose_name_plural': 'Salon Çalışanları',
            },
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('opening_time', models.TimeField(verbose_name='Açılış Saati')),
                ('closing_time', models.TimeField(verbose_name='Kapanış Saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Kapalı')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'unique_together': {('salon', 'day_of_week')},
            },
        ),
    ]
