# Generated by Django 5.2.4 on 2025-07-12 06:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('campaign_type', models.CharField(choices=[('discount', 'İndirim'), ('free_service', 'Ücretsiz Hizmet'), ('bonus_points', 'Bonus Puan'), ('loyalty_discount', 'Sadakat İndirimi')], max_length=20, verbose_name='Kampanya Türü')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Yüzdesi')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirim Tutarı')),
                ('bonus_points', models.IntegerField(blank=True, null=True, verbose_name='Bonus Puan')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('max_usage', models.IntegerField(blank=True, null=True, verbose_name='Maksimum Kullanım')),
                ('current_usage', models.IntegerField(default=0, verbose_name='Mevcut Kullanım')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kupon Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Kupon Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Yüzde İndirim'), ('fixed', 'Sabit İndirim'), ('free_service', 'Ücretsiz Hizmet')], max_length=20, verbose_name='Kupon Türü')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim Yüzdesi')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirim Tutarı')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Tutar')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('max_usage', models.IntegerField(blank=True, null=True, verbose_name='Maksimum Kullanım')),
                ('current_usage', models.IntegerField(default=0, verbose_name='Mevcut Kullanım')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='salons.salon')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
